{% set name = "apache-airflow-providers-salesforce" %}
{% set version = "3.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-salesforce-{{ version }}.tar.gz
  sha256: 69bfa91d776ddccfdf5d1e29e68a8042322951cc6ab00cb6b78809b7c0eb5c11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - pandas >=0.17.1,<1.4
    - simple-salesforce >=1.0.0
    - tableauserverclient

test:
  imports:
    - airflow.providers.salesforce
    - airflow.providers.salesforce.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Salesforce for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-salesforce/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
