{% set name = "apache-airflow-providers-salesforce" %}
{% set version = "5.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_salesforce-{{ version }}.tar.gz
  sha256: c4cfbf90bda0c65e658a172e3e8fb9b1ad43dc7986c9630aada820a426761fb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - pandas >=1.2.5,<2.2
    - simple-salesforce >=1.0.0

test:
  imports:
    - airflow.providers.salesforce
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-salesforce for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/salesforce/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-salesforce/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
